FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends libpq-dev && \
    rm -rf /var/lib/apt/lists/*

COPY backend/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY backend/ ./backend/
COPY usecases/ ./usecases/

ENV PYTHONPATH=/app
EXPOSE 5001

CMD ["uvicorn", \
     "backend.app:app", \
     "--host", "0.0.0.0", \
     "--port", "5001"]
